# This rule is not used by the project namespace-class itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to stanton.sh resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: namespace-class
    app.kubernetes.io/managed-by: kustomize
  name: namespaceclass-viewer-role
rules:
- apiGroups:
  - stanton.sh
  resources:
  - namespaceclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stanton.sh
  resources:
  - namespaceclasses/status
  verbs:
  - get
