apiVersion: akuity.io/v1
kind: NamespaceClass
metadata:
  labels:
    app.kubernetes.io/name: namespace-class
  name: private-network
spec:
  resources:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
        name: web-allow-all
        namespace: default
    spec:
        podSelector:
        matchLabels:
            app: web
        ingress:
        - {}
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
        name: web-allow-from-app
        namespace: default
    spec:
        podSelector:
        matchLabels:
            app: web
        ingress:
        - from:
            - podSelector:
                matchLabels:
                    app: app