apiVersion: stanton.sh/v1
kind: NamespaceClass
metadata:
  labels:
    app.kubernetes.io/name: namespace-class
  name: public-network
spec:
  resources:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: web-allow-all
      namespace: default
    spec:
      podSelector:
        matchLabels:
          app: web
      ingress:
        - {}
